name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false # prevents credential reuse issues
          fetch-depth: 0 # full history for rebase

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: bottomsnode
          outputs: |
            ./assets/github-contribution-grid-snake-dark.svg
            ./assets/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and Push generated SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Pull latest changes before committing
          git pull origin main --rebase || true

          git add assets/
          git commit -m "🐍 Update snake contribution graph" || echo "No changes to commit"

          # Push changes safely with token
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
